# Generated by Django 6.0.1 on 2026-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessiontoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Session Token",
                "verbose_name_plural": "Session Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="totpdevice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "TOTP Device",
                "verbose_name_plural": "TOTP Devices",
            },
        ),
        migrations.RemoveIndex(
            model_name="sessiontoken",
            name="core_sessio_token_438c60_idx",
        ),
        migrations.AddField(
            model_name="sessiontoken",
            name="is_refresh_token_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessiontoken",
            name="refresh_token_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="sessiontoken",
            name="token_hash",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="core_passwo_user_id_19aa2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["token_hash"], name="core_sessio_token_h_c80635_idx"),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(
                fields=["refresh_token_hash"], name="core_sessio_refresh_b87188_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["last_activity"], name="core_sessio_last_ac_ab6ea9_idx"),
        ),
        migrations.AddIndex(
            model_name="totpdevice",
            index=models.Index(fields=["is_confirmed"], name="core_totp_d_is_conf_833524_idx"),
        ),
    ]
