# Generated by Django 6.0.1 on 2026-01-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_default_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={
                "ordering": ["name"],
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_audit__user_id_48e52c_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_audit__organis_25a49d_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="core_audit__action_82b39f_idx",
        ),
        migrations.RemoveIndex(
            model_name="sessiontoken",
            name="core_sessio_last_ac_ab6ea9_idx",
        ),
        migrations.RenameField(
            model_name="emailverificationtoken",
            old_name="is_used",
            new_name="used",
        ),
        migrations.RenameField(
            model_name="passwordresettoken",
            old_name="is_used",
            new_name="used",
        ),
        migrations.RenameField(
            model_name="sessiontoken",
            old_name="last_activity",
            new_name="last_activity_at",
        ),
        migrations.RenameField(
            model_name="sessiontoken",
            old_name="is_used",
            new_name="used",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="avatar_url",
            new_name="avatar",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_created_262184_idx",
            old_name="core_audit__created_ab8951_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordhistory",
            new_name="password_hi_user_id_53e9ab_idx",
            old_name="core_passwo_user_id_19aa2d_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordhistory",
            new_name="password_hi_user_id_f55a03_idx",
            old_name="core_passwo_user_id_cadb28_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordhistory",
            new_name="password_hi_created_f06243_idx",
            old_name="core_passwo_created_5bbcaf_idx",
        ),
        migrations.RenameIndex(
            model_name="sessiontoken",
            new_name="session_tok_user_id_d4ee8f_idx",
            old_name="core_sessio_user_id_c90271_idx",
        ),
        migrations.RenameIndex(
            model_name="sessiontoken",
            new_name="session_tok_token_h_095bc0_idx",
            old_name="core_sessio_token_h_c80635_idx",
        ),
        migrations.RenameIndex(
            model_name="sessiontoken",
            new_name="session_tok_refresh_834291_idx",
            old_name="core_sessio_refresh_b87188_idx",
        ),
        migrations.RenameIndex(
            model_name="sessiontoken",
            new_name="session_tok_token_f_d7fa1d_idx",
            old_name="core_sessio_token_f_2fb8fc_idx",
        ),
        migrations.RenameIndex(
            model_name="sessiontoken",
            new_name="session_tok_device__0d47fe_idx",
            old_name="core_sessio_device__c271f7_idx",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="locale",
        ),
        migrations.AddField(
            model_name="emailverificationtoken",
            name="token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="passwordresettoken",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sessiontoken",
            name="refresh_token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sessiontoken",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="sessiontoken",
            name="token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "-created_at"], name="audit_logs_user_id_6193b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organisation", "-created_at"], name="audit_logs_organis_9c6c15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="audit_logs_action_bcaa71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["slug"], name="core_organi_slug_3088b1_idx"),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["last_activity_at"], name="session_tok_last_ac_8de642_idx"),
        ),
        migrations.AlterModelTable(
            name="auditlog",
            table="audit_logs",
        ),
        migrations.AlterModelTable(
            name="emailverificationtoken",
            table="email_verification_tokens",
        ),
        migrations.AlterModelTable(
            name="passwordhistory",
            table="password_history",
        ),
        migrations.AlterModelTable(
            name="passwordresettoken",
            table="password_reset_tokens",
        ),
        migrations.AlterModelTable(
            name="sessiontoken",
            table="session_tokens",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
