# Generated by Django 6.0.1 on 2026-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_organisation_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="sessiontoken",
            name="session_tok_user_id_d4ee8f_idx",
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(
                fields=["user", "-created_at"], name="session_tok_user_id_84718e_idx"
            ),
        ),
    ]
