# Generated by Django 6.0.1 on 2026-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_remove_sessiontoken_session_tok_user_id_d4ee8f_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "action"], name="audit_logs_user_id_d685f3_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["expires_at"], name="email_verif_expires_770728_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["user", "-created_at"], name="email_verif_user_id_10ad9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["expires_at"], name="password_re_expires_8e96b7_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "-created_at"], name="password_re_user_id_fcb0eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(
                fields=["user", "is_revoked"], name="session_tok_user_id_3ba7b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(fields=["expires_at"], name="session_tok_expires_5b5e2d_idx"),
        ),
        migrations.AddIndex(
            model_name="sessiontoken",
            index=models.Index(
                fields=["is_revoked", "expires_at"], name="session_tok_is_revo_933a28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organisation", "email"], name="core_user_organis_43531c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organisation", "is_active"], name="core_user_organis_0b2914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organisation", "-created_at"], name="core_user_organis_7d4c27_idx"
            ),
        ),
    ]
