# Generated by Django 6.0.1 on 2026-01-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auditlog_audit_logs_user_id_d685f3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
