# Generated by Django 6.0.1 on 2026-01-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backupcode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='totpdevice',
            name='core_totp_d_is_conf_idx',
        ),
        migrations.RenameIndex(
            model_name='backupcode',
            new_name='core_backup_user_id_ba589f_idx',
            old_name='core_backup_user_id_used_idx',
        ),
        migrations.RenameIndex(
            model_name='backupcode',
            new_name='core_backup_code_ha_3f0b12_idx',
            old_name='core_backup_code_hash_idx',
        ),
    ]
