# Generated by Django 6.0.1 on 2026-01-19 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_totpdevice_core_totp_d_is_conf_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when account deletion was requested', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='processing_restricted',
            field=models.BooleanField(default=False, help_text='User has restricted processing of their data (GDPR Article 18)'),
        ),
        migrations.AddField(
            model_name='user',
            name='restricted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when processing was restricted', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restriction_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for processing restriction'),
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the deletion request', max_length=20)),
                ('confirmation_token', models.CharField(blank=True, default='', help_text='Hashed confirmation token (HMAC-SHA256)', max_length=128)),
                ('reason', models.TextField(blank=True, default='', help_text='Optional user-provided reason for deletion')),
                ('data_retained', models.JSONField(blank=True, default=list, help_text='JSON list of data retained for legal compliance (7 years)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when deletion was requested')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Timestamp when deletion was confirmed by user', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when deletion was completed', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the deletion (for admin-initiated deletions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deletions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who requested account deletion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'db_table': 'account_deletion_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='account_del_user_id_6ccf9a_idx'), models.Index(fields=['status', '-created_at'], name='account_del_status_43bb4c_idx'), models.Index(fields=['confirmation_token'], name='account_del_confirm_6a5fb8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('essential', 'Essential (Required)'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing')], help_text='Type of consent (essential, functional, analytics, marketing)', max_length=20)),
                ('granted', models.BooleanField(default=False, help_text='Whether consent is currently granted')),
                ('version', models.CharField(default='1.0.0', help_text='Version of consent policy at time of grant/withdrawal', max_length=20)),
                ('ip_address', models.BinaryField(blank=True, help_text='Encrypted IP address where consent was given/withdrawn', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser user agent string')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when consent was granted')),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='Timestamp when consent was withdrawn', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional consent metadata (referrer, language, etc.)')),
                ('user', models.ForeignKey(help_text='User who gave or withdrew consent', on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'db_table': 'consent_records',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-granted_at'], name='consent_rec_user_id_8d43f1_idx'), models.Index(fields=['user', 'granted'], name='consent_rec_user_id_d968a5_idx'), models.Index(fields=['consent_type', 'granted'], name='consent_rec_consent_62b76b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('granted', True), ('withdrawn_at__isnull', True)), fields=('user', 'consent_type'), name='unique_active_consent_per_type')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', help_text='Current status of the export request', max_length=20)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', help_text='Export file format (JSON or CSV)', max_length=10)),
                ('file_path', models.CharField(blank=True, default='', help_text='Storage path of generated export file', max_length=500)),
                ('download_url', models.CharField(blank=True, default='', help_text='Signed URL for secure file download', max_length=1000)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Timestamp when download URL expires (24 hours from completion)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when request was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when export was completed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional export metadata (file size, record counts, etc.)')),
                ('user', models.ForeignKey(help_text='User who requested the data export', on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'db_table': 'data_export_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='data_export_user_id_8783c2_idx'), models.Index(fields=['status', '-created_at'], name='data_export_status_ff2a4a_idx'), models.Index(fields=['expires_at'], name='data_export_expires_693dcb_idx')],
            },
        ),
    ]
