# Generated by Django 6.0.1 on 2026-01-19 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('acceptable_use', 'Acceptable Use Policy'), ('dpa', 'Data Processing Agreement'), ('sub_processor_list', 'Sub-Processor List'), ('sla', 'Service Level Agreement')], help_text='Type of legal document', max_length=50)),
                ('version', models.CharField(help_text='Semantic version number (e.g., 1.0.0, 2.1.0)', max_length=20)),
                ('title', models.CharField(help_text='Human-readable document title', max_length=255)),
                ('content_hash', models.CharField(help_text='SHA-256 hash of document content for integrity verification', max_length=64)),
                ('content_url', models.URLField(help_text='URL to the full document content', max_length=500)),
                ('effective_date', models.DateTimeField(help_text='Date when this version becomes/became active')),
                ('summary_of_changes', models.TextField(blank=True, default='', help_text='Summary of changes from previous version')),
                ('requires_re_acceptance', models.BooleanField(default=False, help_text='Whether existing users must re-accept this version (material changes)')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this is the currently active version for its type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_documents', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, help_text='Organisation for organisation-specific DPAs (null for platform-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='core.organisation')),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'db_table': 'legal_documents',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was accepted')),
                ('ip_address', models.BinaryField(blank=True, help_text='Encrypted IP address at time of acceptance', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser user agent string at time of acceptance')),
                ('user_email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of user email (for audit after account deletion)', max_length=64)),
                ('acceptance_method', models.CharField(choices=[('checkbox', 'Checkbox Agreement'), ('click_wrap', 'Click-Wrap Agreement'), ('browse_wrap', 'Browse-Wrap Agreement'), ('signed', 'Signed Agreement'), ('api', 'API Acceptance')], default='checkbox', help_text='Method by which acceptance was given', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional acceptance context (referrer, language, etc.)')),
                ('user', models.ForeignKey(blank=True, help_text='User who accepted (null after account deletion)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='Legal document that was accepted (never deleted)', on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='core.legaldocument')),
            ],
            options={
                'verbose_name': 'Legal Acceptance',
                'verbose_name_plural': 'Legal Acceptances',
                'db_table': 'legal_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'is_active'], name='legal_docum_documen_6f1007_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', '-effective_date'], name='legal_docum_documen_ab1ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['organisation', 'document_type'], name='legal_docum_organis_5d2527_idx'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['content_hash'], name='legal_docum_content_767ad9_idx'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type', 'organisation'), name='unique_active_document_per_type_org'),
        ),
        migrations.AddConstraint(
            model_name='legaldocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'version', 'organisation'), name='unique_version_per_document_type_org'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['user', 'document'], name='legal_accep_user_id_aa51ef_idx'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['user', '-accepted_at'], name='legal_accep_user_id_b67cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['document', '-accepted_at'], name='legal_accep_documen_e5ad1e_idx'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['user_email_hash'], name='legal_accep_user_em_beaa21_idx'),
        ),
        migrations.AddIndex(
            model_name='legalacceptance',
            index=models.Index(fields=['accepted_at'], name='legal_accep_accepte_5a111b_idx'),
        ),
    ]
